controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    bot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController  # Changed from GripperActionController

bot_arm_controller:
  ros__parameters:
    joints:
      - top_plate_joint
      - lower_arm_joint
      - upper_arm_joint
      - wrist_joint
      - claw_base_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

hand_controller:
  ros__parameters:
    joints:  # Changed from "joint:" to "joints:"
      - right_claw_joint
      - left_claw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    joints:
      - top_plate_joint
      - lower_arm_joint
      - upper_arm_joint
      - wrist_joint
      - claw_base_joint
      - right_claw_joint
      - left_claw_joint