# Default initial positions for cobot's ros2_control system

initial_positions:
  top_plate_joint: 3.1200
  lower_arm_joint: 1.0000
  upper_arm_joint: 0.6000
  wrist_joint: -1.7000
  claw_base_joint: 0.0000
  right_claw_joint: 0.0000
  left_claw_joint: 0.0000


# way_points_1={3.12,1.0,0.6,-1.7,0.0,0.0,0.0}
# way_points_2={3.365,1.636,-0.542,-1.700,0.00,0.00,0.00}
# way_points_3={3.365,2.074,-1.479,-1.70,0.00,0.00,0.00}
# way_points_4={3.365,2.074,-1.479,-1.570,0.00,0.00,0.00}
# way_points_5={}

# self.INITIAL_POSITION = [3.365, 1.636, -0.542, -1.700, 0.000]

#         # 2. Approach Waypoint 2
#         self.WAYPOINT_2 = [3.365, 2.074, -1.479, -1.700, 0.000]
        
#         # 3. Approach Waypoint 3 (Wrist rotates to -1.57)
#         self.WAYPOINT_3 = [3.365, 2.074, -1.479, -1.570, 0.000]
#         self.WAYPOINT_4 = [3.449, 1.434, -1.204, -1.296, 0.000]